
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Studente
 */
public class NewJFrame extends javax.swing.JFrame {
    
    /* Distributore's declaration */
    Distributore dist;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        btnOnOff = new javax.swing.JButton();
        btnCappuccino = new javax.swing.JButton();
        btnGettoni = new javax.swing.JButton();
        btnCaffe = new javax.swing.JButton();
        numGettoni = new javax.swing.JLabel();
        numCaffe = new javax.swing.JLabel();
        numCappuccino = new javax.swing.JLabel();
        btnResto = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        numTotGettoni = new javax.swing.JLabel();
        totGettoni = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        title.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Distributore Automatico");
        title.setToolTipText("This is your personal caffeine distributor");
        title.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        title.setMaximumSize(new java.awt.Dimension(210, 45));
        title.setMinimumSize(new java.awt.Dimension(210, 45));
        title.setPreferredSize(new java.awt.Dimension(210, 45));

        btnOnOff.setBackground(new java.awt.Color(255, 0, 0));
        btnOnOff.setText("Off");
        btnOnOff.setToolTipText("This button will turn on/off the machine");
        btnOnOff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOnOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOnOffMouseClicked(evt);
            }
        });

        btnCappuccino.setText("Cappuccino");
        btnCappuccino.setEnabled(false);
        btnCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCappuccinoMouseClicked(evt);
            }
        });

        btnGettoni.setText("Gettoni");
        btnGettoni.setEnabled(false);
        btnGettoni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGettoniMouseClicked(evt);
            }
        });

        btnCaffe.setText("Caffé");
        btnCaffe.setEnabled(false);
        btnCaffe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCaffeMouseClicked(evt);
            }
        });

        numGettoni.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numGettoni.setText("0");

        numCaffe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numCaffe.setText("10");

        numCappuccino.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numCappuccino.setText("10");

        btnResto.setText("Restituzione");
        btnResto.setEnabled(false);
        btnResto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRestoMouseClicked(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.setEnabled(false);
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });

        numTotGettoni.setText("0");
        numTotGettoni.setToolTipText("This line will show the coins inside the machine");

        totGettoni.setText("Totale Gettoni");
        totGettoni.setToolTipText("This line will show the coins inside the machine");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnResto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOnOff))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnReset))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(totGettoni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numTotGettoni))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCappuccino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGettoni)
                        .addGap(113, 113, 113)
                        .addComponent(numGettoni, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCaffe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numCaffe, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGettoni)
                    .addComponent(numGettoni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaffe)
                    .addComponent(numCaffe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCappuccino)
                    .addComponent(numCappuccino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numTotGettoni)
                    .addComponent(totGettoni))
                .addGap(8, 36, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOnOff)
                    .addComponent(btnResto)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        dist = new Distributore();
    }//GEN-LAST:event_formWindowOpened

    private void btnOnOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOnOffMouseClicked
        // TODO add your handling code here:
        dist.accensioneSpegnimento();
        if(dist.isAcceso()){
            btnOnOff.setBackground(Color.GREEN);
            btnOnOff.setText("On");
            btnCappuccino.setEnabled(true);
            btnCappuccino.setToolTipText("This button will insert a coin");
            btnGettoni.setEnabled(true);
            btnGettoni.setToolTipText("This button will pick a coffee");
            btnCaffe.setEnabled(true);
            btnCaffe.setToolTipText("This button will pick a cappuccino");
            btnResto.setEnabled(true);
            btnResto.setToolTipText("This button will refund you");
            btnReset.setEnabled(true);
            btnReset.setToolTipText("This button will reset the machine");
        }else{
            btnOnOff.setBackground(Color.RED);
            btnOnOff.setText("Off");
            btnCappuccino.setEnabled(false);
            btnCappuccino.setToolTipText(null);
            btnGettoni.setEnabled(false);
            btnGettoni.setToolTipText(null);
            btnCaffe.setEnabled(false);
            btnCaffe.setToolTipText(null);
            btnResto.setEnabled(false);
            btnResto.setToolTipText(null);
            btnReset.setEnabled(false);
            btnReset.setToolTipText(null);
        }
    }//GEN-LAST:event_btnOnOffMouseClicked

    private void btnGettoniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGettoniMouseClicked
        // TODO add your handling code here:
        dist.inserimentoGettone();
        numGettoni.setText(String.valueOf(dist.getCredito()));
        numTotGettoni.setText(String.valueOf(dist.getTotGettoni()));
    }//GEN-LAST:event_btnGettoniMouseClicked

    private void btnCaffeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCaffeMouseClicked
        // TODO add your handling code here:
        dist.prendiCaffe();
        numGettoni.setText(String.valueOf(dist.getCredito()));
        numCaffe.setText(String.valueOf(dist.getCaffe()));
    }//GEN-LAST:event_btnCaffeMouseClicked

    private void btnCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCappuccinoMouseClicked
        // TODO add your handling code here:
        dist.prendiCappuccino();
        numGettoni.setText(String.valueOf(dist.getCredito()));
        numCappuccino.setText(String.valueOf(dist.getCappuccino()));
    }//GEN-LAST:event_btnCappuccinoMouseClicked

    private void btnRestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestoMouseClicked
        // TODO add your handling code here:
        dist.restituisciCredito();
        numGettoni.setText(String.valueOf(dist.getCredito()));
        numTotGettoni.setText(String.valueOf(dist.getTotGettoni()));
    }//GEN-LAST:event_btnRestoMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
        dist.svuotaERicarica();
        numGettoni.setText(String.valueOf(dist.getCredito()));
        numCaffe.setText(String.valueOf(dist.getCaffe()));
        numCappuccino.setText(String.valueOf(dist.getCappuccino()));
        numTotGettoni.setText(String.valueOf(dist.getTotGettoni()));
    }//GEN-LAST:event_btnResetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaffe;
    private javax.swing.JButton btnCappuccino;
    private javax.swing.JButton btnGettoni;
    private javax.swing.JButton btnOnOff;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnResto;
    private javax.swing.JLabel numCaffe;
    private javax.swing.JLabel numCappuccino;
    private javax.swing.JLabel numGettoni;
    private javax.swing.JLabel numTotGettoni;
    private javax.swing.JLabel title;
    private javax.swing.JLabel totGettoni;
    // End of variables declaration//GEN-END:variables
}
